services:
  docker:
    image: docker:dind
    privileged: true

pipeline:
  build:
    image: docker
    environment:
      - DOCKER_HOST=tcp://docker:2375
    commands:
      - docker build -t devbuild .

  test:
    image: docker
    environment:
      - DOCKER_HOST=tcp://docker:2375
    commands:
      - docker run --rm devbuild /bin/sh -xec "test \"$(echo /lib/libssl*.so*)\" != '/lib/libssl*.so*'"
      - docker run --rm devbuild /bin/sh -xec "test \"$(echo /lib/libcrypto*.so*)\" != '/lib/libcrypto*.so*'"
      - docker run --rm devbuild /bin/sh -xec "openssl version"

  publish:
    image: docker
    secrets: [ DOCKER_USER, DOCKER_PASS ]
    environment:
      - DOCKER_HOST=tcp://docker:2375
    commands:
      - docker login -u $DOCKER_USER -p $DOCKER_PASS
      - docker tag devbuild adamant/busybox:libressl
      - docker push adamant/busybox

  downstream:
    image: plugins/downstream
    when:
      event: [push, tag, deployment]
    secrets: [ DOWNSTREAM_TOKEN ]
    server: https://drone.adam-ant.co.uk
    fork: true
    repositories:
      - Adam-Ant/docker-plex-tiny@master
      - Adam-Ant/docker-plex-tiny@pass
    when:
      event:  [ push, tag, deployment]
      status: [ success ]
