pipeline:
  build:
    image: spritsail/docker-build
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    repo: busybox-lssl-dev

  test:
    image: docker
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    commands:
      - docker run --rm busybox-lssl-dev /bin/sh -xec "test \"$(echo /lib/libssl*.so*)\" != '/lib/libssl*.so*'"
      - docker run --rm busybox-lssl-dev /bin/sh -xec "test \"$(echo /lib/libcrypto*.so*)\" != '/lib/libcrypto*.so*'"
      - docker run --rm busybox-lssl-dev /bin/sh -xec "openssl version"

  publish:
    image: spritsail/docker-publish
    when: { branch: [ master, libressl ], event: [ push, tag, deployment ] }
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    secrets: [ docker_username, docker_password, microbadger_token ]
    from: busybox-lssl-dev
    repo: spritsail/busybox:libressl

  downstream:
    image: plugins/downstream
    when: { status: [ success ], event: [ push, tag, deployment ] }
    secrets: [ downstream_token ]
    server: https://drone.spritsail.io
    fork: true
    repositories:
      - spritsail/plex-media-server@master
      - spritsail/plex-media-server@pass
      # TODO: Update AMP build and re-enable downstream
      #- spritsail/amp

  notify:
    image: appleboy/drone-telegram
    when: { status: [ success, failure ] }
    secrets: [ telegram_token, telegram_to ]
    message: |
      *{{repo.owner}}/{{repo.name}} [{{commit.branch}}]*: Build #{{build.number}}: *{{uppercase build.status}}*
      {{build.link}}
